name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: 3.3.0
  cloud_firestore: ^4.17.3
  cloud_functions: ^4.7.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  easystate: ^1.0.2
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.5
  firebase_ui_database: ^1.4.3
  firebase_ui_firestore: ^1.6.3
  fireflutter:
    path: ..
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.3

  intl: ^0.19.0
  phone_sign_in:
    path: ../apps/phone_sign_in

  social_design_system:
    path: ../apps/social_design_system
  typesense: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter



flutter:
  uses-material-design: true
