name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: 3.3.0
  cloud_firestore: 5.0.1
  cloud_functions: 5.0.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: 5.1.0
  firebase_core: 3.1.0
  firebase_database: 11.0.1
  firebase_messaging: 15.0.1
  firebase_storage: 12.0.1
  firebase_ui_database: ^1.4.3
  firebase_ui_firestore: ^1.6.3
  fireflutter:
    path: ..
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.3

  intl: ^0.19.0
  phone_sign_in:
    path: ../apps/phone_sign_in

  social_design_system:
    path: ../apps/social_design_system
  typesense: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter



flutter:
  uses-material-design: true
