name: fireship
description: "A lightning-fast, robust CMS for seamless real-time content management in app development."
version: 0.0.1
homepage: https://github.com/thruthesky/fireship

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_ui_database: ^1.3.13
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  material_color_utilities: ^0.5.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
