name: fireship
description: "A lightning-fast, robust CMS for seamless real-time content management in app development."
version: 0.0.1
homepage: https://github.com/thruthesky/fireship

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
