name: fireflutter
description: A complete, open source, rapid development package for creating apps like CMS(content management system), social, chat, forum, shopping mall based on Firebase.
version: 0.3.10
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.1.0
  chewie: ^1.7.0
  cloud_firestore: ^4.8.4
  crypto: ^3.0.3
  file_picker: ^5.3.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.5
  firebase_ui_database: ^1.3.7
  firebase_ui_firestore: ^1.5.4
  firebase_ui_localizations: ^1.5.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  linkify: ^5.0.0
  mime_type: ^1.0.0
  path: ^1.8.3
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  # This is needed for `display_media/dislay_media.dart`
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
