name: fireflutter
description: A free, open source, complete, rapid development package for creating Social apps, Chat apps, Community(Forum) apps, Shopping mall apps, and much more based on Firebase.
version: 0.3.3
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.8.4
  file_picker: ^5.3.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.5
  firebase_ui_firestore: ^1.5.4
  firebase_ui_localizations: ^1.5.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  image_picker: ^1.0.2
  intl: ^0.18.0
  rxdart: ^0.27.7
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
