name: fireflutter
description: "A lightning-fast, robust CMS for seamless real-time content management in app development."
version: 0.3.29
homepage: https://github.com/thruthesky/fireflutter
repository: https://github.com/thruthesky/fireflutter
issue_tracker: https://github.com/thruthesky/fireflutter/issues
screenshots:
  - description: The rapid flutter app development kit.
    path: assets/screenshots/logo.jpg

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_links: ^4.0.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.17.3
  cloud_functions: ^4.7.4
  crypto: ^3.0.3
  devicelocale: ^0.7.0
  dio: ^5.4.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.5
  firebase_ui_database: ^1.4.3
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_linkify: ^6.0.0
  geohash_plus: ^1.1.1
  html: ^0.15.4
  http: ^1.2.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  linkify: ^5.0.0
  material_color_utilities: ^0.8.0
  rxdart: ^0.27.7
  share_plus: ^8.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  lints: ^3.0.0

flutter:
