name: fireflutter

description: A free, open source, complete, rapid development package for creating Social apps, Chat apps, Community(Forum) apps, Shopping mall apps, and much more based on Firebase.
version: 0.4.0
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_database: ^10.2.1
  firebase_ui_database: ^1.3.1
  flutter_layout_grid: ^2.0.3
  go_router: ^7.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
